language: php

php:
    #- "5.5"
    - "5.4"

before_install:
    # - composer selfupdate #seems tbd automatically
    - sudo apt-get update
    - sudo apt-get install libssh2-1 libssh2-1-dev
    - printf "\n" | pecl install ssh2 channel://pecl.php.net/ssh2-0.13
    # - sudo apt-get install libssh2-php

install: composer update --prefer-dist --no-interaction

script:
    - phpunit --coverage-text
